[program:web]
environment=HOME="/home/user"
command=yarn dev
user=user
directory=/home/user/project/apps/web
autostart=true
autorestart=true
stdout_logfile=/var/log/web.log
stderr_logfile=/var/log/web-err.log
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:mobile]
environment=HOME="/home/user",EXPO_NO_CACHE=1,EXPO_USE_FAST_RESOLVER=1,EAS_NO_VCS=1,EAS_PROJECT_ROOT=.,EXPO_NO_METRO_LAZY=1
command=yarn run expo start --port 8081
user=user
directory=/home/user/project/apps/mobile
autostart=true
autorestart=true
stdout_logfile=/var/log/mobile.log
stderr_logfile=/var/log/mobile-err.log
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:healthcheck]
command=node /usr/local/bin/healthcheck.mjs
user=root
autostart=true
autorestart=true
startsecs=1
stdout_logfile=/tmp/healthcheck.log
stdout_logfile_maxbytes=10KB
stderr_logfile=/tmp/healthcheck-err.log
stderr_logfile_maxbytes=10KB

[program:vector]
command=/usr/local/bin/wait-and-start-vector.sh
user=vector
autostart=true
autorestart=true
stdout_logfile=/tmp/vector.log
stdout_logfile_maxbytes=10KB
stderr_logfile=/tmp/vector-err.log
stderr_logfile_maxbytes=10KB

[supervisord]
nodaemon=true                  ; <— foreground (preferred in containers)
loglevel=debug                  ; supervisord logs go to stderr in nodaemon=true
pidfile=/var/run/supervisord.pid
childlogdir=/tmp
